name: LilyEssentials
version: 1.2
description: Essential Commands and Features for LilyPad!
authors: [The_Zip, Matthijs110, Tzeentchful, shawshark, Horrgs, charries96]
main: com.bobacadodl.lilyessentials.LilyEssentials
depend: [LilyPad-Connect]
commands:
  message:
    aliases: [msg, tell, whisper, m, emsg]
    description: Private-message a player
  send:
    description: Send a player to another server
  sendall:
    description: Send all players to another server
  find:
    aliases: [find, whereis]
    description: Find what server another player is on
  alert:
    description: Network wide broadcast
  alertserver:
    description: MultiServer broadcast
  reply:
    aliases: [r,repl]
    description: Reply back to another player
  admin:
    aliases: [a]
    description: Admin only chat
  dispatch:
    description: Dispatch a command to all servers
  dispatchserver:
    description: Dispatch a command to specific servers
  glist:
    aliases: [globallist, listall, servers]
    description: Global player list
  ignore:
    description: Ignore someone.
  hide:
    description: Hide from the players of the sever.
permissions:
  lilyesssentials.*:
    description: All LilyEssentials perms
    children:
      lilyessentials.general.message: true
      lilyessentials.general.glist: true
      lilyessentials.general.find: true
      lilyessentials.admin.chat: true
      lilyessentials.admin.send: true
      lilyessentials.admin.sendall: true
      lilyessentials.admin.alert: true
      lilyessentials.admin.alertserver: true
      lilyessentials.admin.dispatch: true
      lilyessentials.admin.dispatchserver: true
  lilyessentials.general.*:
    description: All general LilyEssentials perms
    children:
      lilyessentials.general.message: true
      lilyessentials.general.find: true
      lilyessentials.general.glist: true
  lilyessentials.admin.*:
    description: All admin LilyEssentials perms
    children:
      lilyessentials.admin.chat: true
      lilyessentials.admin.alert: true
      lilyessentials.admin.alertserver: true
      lilyessentials.admin.dispatch: true
      lilyessentials.admin.dispatchserver: true
      lilyessentials.admin.send: true
      lilyessentials.admin.sendall: true
      lilyessentials.admin.hide: true
      lilyessentials.admin.socialspy: true
  lilyessentials.admin.chat:
    description: Access to adminChat
    default: op
  lilyessentials.admin.alert:
    description: Access to alert
    default: op
  lilyessentials.admin.alertserver:
    description: Access to alertserver
    default: op
  lilyessentials.admin.dispatch:
    description: Access to dispatch
    default: op
  lilyessentials.admin.dispatchserver:
    description: Access to dispatchserver
    default: op
  lilyessentials.general.message:
    description: Access to messaging
    default: true
  lilyessentials.general.glist:
    description: Global server playerlist
    default: true
  lilyessentials.general.find:
    description: find another player
    default: true
  lilyessentials.admin.send:
    description: send a player to another server
    default: op
  lilyessentials.admin.hide:
    description: hides the player from messages
    default: op
